services:
  - type: web
    name: sp-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:create_app()
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        scope: shared
